// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oppurtunityshield.Infrastructure.Data;

#nullable disable

namespace Oppurtunityshield.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("InputType")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<string>("OpportunityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrustScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Impact")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("EvidenceItems");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualOutcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasHelpful")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisResultId");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Analysis", b =>
                {
                    b.OwnsMany("Oppurtunityshield.Domain.Entities.ProgressStep", "ProgressSteps", b1 =>
                        {
                            b1.Property<Guid>("AnalysisId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AnalysisId", "__synthesizedOrdinal");

                            b1.ToTable("Analyses");

                            b1.ToJson("ProgressSteps");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisId");
                        });

                    b.Navigation("ProgressSteps");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("Oppurtunityshield.Domain.Entities.Analysis", "Analysis")
                        .WithOne("Result")
                        .HasForeignKey("Oppurtunityshield.Domain.Entities.AnalysisResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("Oppurtunityshield.Domain.Entities.AnalysisResult", "AnalysisResult")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Oppurtunityshield.Domain.Entities.Analysis", "Analysis")
                        .WithOne("Feedback")
                        .HasForeignKey("Oppurtunityshield.Domain.Entities.Feedback", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Signal", b =>
                {
                    b.HasOne("Oppurtunityshield.Domain.Entities.AnalysisResult", "AnalysisResult")
                        .WithMany("Signals")
                        .HasForeignKey("AnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisResult");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Oppurtunityshield.Domain.Entities.AnalysisResult", b =>
                {
                    b.Navigation("EvidenceItems");

                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
